name = "simple_izhikevich"
uuid = "c163be58-066b-4041-9e40-4806cc95bff1"
authors = ["alexPatrie <alexanderpatrie@gmail.com>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
